---
- name: install nrpe
  package:
    name: "nrpe"
    state: present

- name: enable nrpe autostart
  service:
    name: nrpe
    enabled: yes

- name: delete default user nagios
  user:
    name: nagios
    state: absent
  tags: user
  ignore_errors: True

- name: create nrpe-user
  user:
    name: nrpe
    shell: /sbin/nologin
    group: nrpe
  tags:
    - init
    - user

- name: check if group exists
  shell: "cut -d: -f1 /etc/group"
  changed_when: false
  check_mode: no
  register: existing_groups

- name: create nrpe-user
  user:
    name: nrpe
    groups: "{{ item }}"
    append: yes
  with_items:
    - "{{nrpe_additional_groups}}"
  when: item in existing_groups.stdout_lines

- name: make sure that libexec-dir and nrpe.d is created
  file:
    path: "{{ item }}"
    state: directory
    owner: nrpe
    group: nrpe
    mode: 0750
  with_items:
    - "/var/run/nagios/"
    - "/home/nrpe/"
    - "{{ nagios_plugins_directory }}"
    - "/etc/nagios/nrpe.d/"

- name: copy over non-packaged checks
  copy:
    src: ../files/checks/
    dest: "{{ nagios_plugins_directory }}"
    owner: "nrpe"
    group: "nrpe"

- name: copy over base NRPE checks config file
  copy:
    src: groups/
    dest: /etc/nagios/nrpe.d/
    owner: nrpe
    group: nrpe
    mode: 0750 
  notify: restart nrpe

- name: copy over standard nrpe config
  template:
    src: nrpe.cfg
    dest: /etc/nagios/nrpe.cfg
    owner: nrpe
    group: nrpe
    mode: 0750 
  notify: restart nrpe
