---
- name: install nrpe
  package:
    name: "nrpe"
    state: present

- name: start nrpe and enable autostart
  service:
    name: nrpe
    enabled: yes

- name: delete default user nagios
  user:
    name: nagios
    state: absent
  tags: user
  ignore_errors: True

- name: create nrpe-user
  user:
    name: "{{ nrpe_user }}"
    group: "{{ nrpe_group }}"
    shell: /sbin/nologin
  tags:
    - init
    - user

- name: get all existing groups from the system
  shell: "cut -d: -f1 /etc/group"
  changed_when: false
  check_mode: no
  register: existing_groups

- name: add nrpe user to additional groups
  user:
    name: "{{ nrpe_user }}"
    groups: "{{ item }}"
    append: yes
  with_items:
    - "{{ nrpe_additional_groups }}"
  when: item in existing_groups.stdout_lines

- name: make sure that directories are created
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nrpe_user }}"
    group: "{{ nrpe_group }}"
    mode: 0750
  with_items:
    - "/var/run/nagios/"
    - "/home/{{ nrpe_user }}/"
    - "/etc/nagios/"
    - "/etc/nrpe.d/"
    - "{{ nrpe_plugins_directory }}"

- name: copy over non-packaged checks
  git:
    repo: "{{ nrpe_checks_repository }}"
    dest: "{{ nrpe_plugins_directory }}"
    force: true
  when: nrpe_checks_repository is defined

- name: change permissions of downloaded checks
  file:
    path: "{{ nrpe_plugins_directory }}"
    owner: "{{ nrpe_user }}"
    group: "{{ nrpe_group }}"
    mode: 0750
    recurse: true
  when: nrpe_checks_repository is defined

- name: copy over base NRPE checks config file
  template:
    src: "nrpe-checks.cfg"
    dest: "/etc/nrpe.d/nrpe-checks.cfg"
    owner: "{{ nrpe_user }}"
    group: "{{ nrpe_group }}"
    mode: 0750
  when: nrpe_check_list is defined
  notify: restart nrpe

- name: create standard nrpe configuration
  template:
    src: "nrpe.cfg"
    dest: "/etc/nagios/nrpe.cfg"
    owner: "{{ nrpe_user }}"
    group: "{{ nrpe_group }}"
    mode: 0750
  notify: restart nrpe
