#!/bin/bash

DEBUG=0


function debug {
if [ "$DEBUG" -eq "1" ] ; then
        echo $1
fi

}
RGROUPNAME=`sudo /usr/sbin/crm_resource --quiet -L |grep "Resource Group:"|gawk -F' ' {'print $3'}`
STICKINESS=`sudo /usr/sbin/crm_attribute -G -n default-resource-stickiness -Q`
FAIL_STICKINESS=`sudo /usr/sbin/crm_attribute -G -n default-resource-failure-stickiness -Q`
PRIMARY=`sudo /usr/sbin/crmadmin -D |gawk -F' ' {'print $4'}`
NODES=(`sudo /usr/sbin/crmadmin -N |gawk -F' ' {'print $3'}`)
cnt=${#NODES[@]}
for (( i = 0 ; i < cnt ; i++ ))
do
        if [ ${NODES[i]} = $PRIMARY ] ;then
                debug "starting resourcecheck for Node ${NODES[i]}"
                RESULT="0"
                RESOURCE=(`sudo /usr/sbin/crm_resource --quiet -L |grep -v "Resource Group:"|gawk -F' ' {'print $1'}`)
                rcnt=${#RESOURCE[@]}
                for (( j = 0 ; j < rcnt ; j++ ))
                do
                        FAILS=`sudo /usr/sbin/crm_failcount -Q -G -U ${NODES[i]} -r ${RESOURCE[j]} 2> /dev/null`
                        if [ "$?" -ne "0" ] ; then
                                FAILS="0"
                        fi
                        if [ "$FAILS" -eq "0" ] ; then
                                let "RESULT = ${RESULT} + $STICKINESS"
                        else
                                let "RESULT = ${RESULT} + $FAIL_STICKINESS * $FAILS"
                        fi
                        debug "${NODES[i]} :: ${RESOURCE[j]} -> $FAILS (${RESULT})"
                done

                debug "${NODES[i]} -> ${RESULT}"
        fi
done
echo "stickiness: ${RESULT} / 0"
if [ "${RESULT}" -lt "1500" ];then
        exit 2
else
        exit 0
fi

