#!/bin/bash
#
# Check for open files.
# WARN and CRIT are percentage values, e.g. LIMIT=1000 files,
# WARN=50 means WARNING-message at 500 files
#set -x
WARN=$1
CRIT=$2
USER=$3
COUNT=0

#check for arguments
if [ $# -eq 0 ]; then
        echo "Missing arguments."
        echo "Usage: $0 \$WARN \$CRIT \$USER"
        exit 1
fi

LIMIT=$(sudo -u $USER sh -c "ulimit -n")
COUNT=$(sudo /usr/sbin/lsof -u "$USER" | wc -l)

CRIT_THRES=$(echo "scale=0;${LIMIT}/100*${CRIT}" | bc)
WARN_THRES=$(echo "scale=0;${LIMIT}/100*${WARN}" | bc)
PERCENTAGE=$(echo "scale=2;${COUNT}/(${LIMIT}/100)" | bc)

if [ $COUNT -gt $WARN_THRES ]; then
        if [ $COUNT -gt $CRIT_THRES ]; then
                echo "CRITICAL: Too many open files! Open files: $COUNT Limit: $LIMIT | Percentage: $PERCENTAGE"
                exit 2
        else
                echo "WARNING: Too many open files! Open files: $COUNT Limit: $LIMIT | Percentage: $PERCENTAGE"
                exit 1
        fi
else
        echo "OK: Open files: $COUNT Limit: $LIMIT | Percentage: $PERCENTAGE"
        exit 0
fi

