#!/bin/bash

CGROUPS=($(ps -o user:50,cgroup $(awk -F: '/^mysql.*/ {printf "-U %s ",$1}' /etc/passwd) --no-header))

OUTERROR=""

for (( I=0 ; I < ${#CGROUPS[*]}/2 ; I++ ))
do
	OKCOUNT=0
	SUMCOUNT=0
	OUTGROUPS=""
	#echo -e "User:" ${CGROUPS[$I*2]} "...\n"
	for ASSIGN in $(echo ${CGROUPS[$I*2+1]} | tr ";" " ")
	do
		((SUMCOUNT++))
		# Wenn Nutzername in CGroup Assignment enthalten
		if [[ $ASSIGN =~ "${CGROUPS[$I*2]}" ]]
		then
			((OKCOUNT++))
		else
			OUTGROUPS="${OUTGROUPS}$(echo $ASSIGN | cut -d: -f1),"
		fi
		#echo -e "\tAssign" $ASSIGN "...\n"
	done
	# Probleme behandeln
	if [ $OKCOUNT -ne $SUMCOUNT -o $OKCOUNT -eq 0 ]
	then
		OUTERROR="${OUTERROR}User: ${CGROUPS[$I*2]} (CGroups: ${OUTGROUPS%\,}) "
	fi
done

if [ "$OUTERROR" != "" ]
then
	echo "CRITICAL - Fehlerhafte Zuordnung ${OUTERROR}"
	exit 2
else
	echo "OK - Alle CGroups korrekt zugeordnet"
	exit 0
fi
