#!/bin/bash
#
# SF070 Nagios NRPE script
# NRPE cluster synchronization check scripts
#  - check_etcdir.sh
#  - script will check the files in $etcDirectoriesToBeinSync
#  - preconditions: HOST1/HOST2 need to have SSH key authentication without password for NRPE user (usally 'nagios') in place
#

CONFIGURATION="undefined"

while getopts "c:" opt; do
        case $opt in
                c)
                        CONFIGURATION=$OPTARG
                ;;
        esac
done

if [ ! -f $CONFIGURATION ]; then
        echo "Configuration ${CONFIGURATION} not found."
        exit 3
fi

source $CONFIGURATION

PRUNE_FILE=""
if [ -n "${ignoredFiles}" ]; then
        PRUNE_FILE+=$(echo -n $ignoredFiles |xargs -d' ' -n1 -I FILE echo -n " ! -name FILE " )
fi

PRUNE_DIR=""
if [ -n "${ignoredDirs}" ]; then
        PRUNE_DIR+=$(echo -n $ignoredDirs |xargs -d' ' -n1 -I DIR echo -n " ! -name DIR " )
fi

# Compare directories
diff <(find $etcDirectoriesToBeInSync $PRUNE_FILE -type f  -exec md5sum {} \; | sort +1 -2) <(ssh $othernode "find $etcDirectoriesToBeInSync $PRUNE_FILE -type f -exec md5sum {} \; | sort +1 -2") > /tmp/etcdir_comp_md5.txt 2>&1
EC1=$?
diff <(find $etcDirectoriesToBeInSync $PRUNE_DIR -type d | sort) <(ssh $othernode "find $etcDirectoriesToBeInSync $PRUNE_DIR -type d | sort") > /tmp/etcdir_comp.txt 2>&1
EC2=$?

CHECK_FILE=`grep -P "^<" /tmp/etcdir_comp_md5.txt | grep -o -P "/.*[A-Za-z].*$" | tr '\n' ' '`;
CHECK_DIRECTORY=`grep -P "^<" /tmp/etcdir_comp.txt | grep -o -P " .*[A-Za-z0-9]" | tr '\n' ' '`;

rm -f /tmp/etcdir_comp_md5.txt /tmp/etcdir_comp.txt

# Evaluation
if [ $EC1 -eq 0 -a $EC2 -eq 0 ]; then
    echo "OK: The configured configuration directories/files are synchronous on $HOST1 and $HOST2."
    exit 0
else
    if [ $EC1 -eq 1 ]; then
        if [ -z "$CHECK_FILE" ]; then
            echo "FAILED: File(s) missing on this node (${thisnode}). Please check the other node ($othernode)!"
            exit 1
        else
            echo "FAILED: File '$CHECK_FILE' need to be checked."
            exit 2
        fi

    fi

    if [ $EC2 -eq 1 ]; then
        if [ -z "$CHECK_DIRECTORY" ]; then
            echo "FAILED: Directory(s) missing on this node (${thisnode}). Please check the other node ($othernode)!"
            exit 1
        else
            echo "FAILED: Directory '$CHECK_DIRECTORY' missing."
            exit 2
        fi
    fi

    if [ $EC1 -ne 1 -o $EC2 -ne 1 ]; then
        echo "Internal Error: Failed to diff files through ssh/local."
        exit 3
    fi
fi

