#!/bin/bash
	HOSTNAME=`uname -n | tr "[:upper:]" "[:lower:]"`
        RESOURCE=$1
        stat=`sudo /usr/sbin/crm_mon -1|grep -m1 ${RESOURCE}|gawk -F' ' {'print $3'}`
	NODE=`sudo /usr/sbin/crm_mon -1|grep -m1 ${RESOURCE}|gawk -F' ' {'print $4'}`
	FAILS=`sudo /usr/sbin/crm_failcount -Q -G -U ${NODE} -r ${RESOURCE} 2> /dev/null`
	if [ "$?" -ne "0" ] ; then
	        FAILS="0"
        fi

        case $stat in
                *"Started"*)
			if [ ${HOSTNAME} = ${NODE} ] ;then
				echo "${RESOURCE} is running on ${NODE} Fails: ${FAILS}"
                                rc=0
			else
				echo "${RESOURCE} is running on ${NODE} Fails: ${FAILS}"
				rc=1
			fi
			if [ ${FAILS} -gt 1 ] ;then
				rc=1
			fi
                        rc=$rc;;
                *"FAILED"*)
                        echo "${RESOURCE} is not running on ${NODE}"
                        rc=2;;
                *)
                        echo "${RESOURCE} is not running on ${NODE}"
                        rc=2;;
        esac

exit $rc

