#!/bin/bash
#
# Check for open processes.
# WARN and CRIT are percentage values, e.g. LIMIT=1000 processes,
# WARN=50 means WARNING-message at 500 processes
#set -x
WARN=$1
CRIT=$2
USER=$3
COUNT=0

#check for arguments
if [ $# -eq 0 ]; then
        echo "Missing arguments."
        echo "Usage: $0 \$WARN \$CRIT \$USER"
        exit 1
fi

LIMIT=$(su - $USER -s /bin/bash -c "ulimit -u")
COUNT=$(ps -LU $USER -Lu $USER u | wc -l)

if [[ ! $LIMIT =~ ^-?[0-9]+$ ]]; then
        echo "Fehler! Konnte offene Prozesse nicht auslesen."
        exit 1
fi

if [[ ! $COUNT =~ ^-?[0-9]+$ ]]; then
        echo "Fehler! Konnte offene Prozesse nicht auslesen."
        exit 1
fi

CRIT_THRES=$(echo "scale=0;${LIMIT}/100*${CRIT}" | bc)
WARN_THRES=$(echo "scale=0;${LIMIT}/100*${WARN}" | bc)
PERCENTAGE=$(echo "scale=2;${COUNT}/(${LIMIT}/100)" | bc)

if [ $COUNT -gt $WARN_THRES ]; then
        if [ $COUNT -gt $CRIT_THRES ]; then
                echo "CRITICAL: Too many open processes! Open processes: $COUNT Limit: $LIMIT | Percentage: $PERCENTAGE"
                exit 1
        else
                echo "WARNING: Too many open processes! Open processes: $COUNT Limit: $LIMIT | Percentage: $PERCENTAGE"
                exit 2
        fi
else
        echo "OK: Open processes: $COUNT Limit: $LIMIT | Percentage: $PERCENTAGE"
        exit 0
fi
