#!/bin/bash

## Set HA Properties

MASTER=$1
SLAVE=$2


## GO

COUNT=`/usr/bin/sudo /usr/sbin/crm_mon -s | /bin/grep $SLAVE | /bin/grep -vi node | grep -v "Current DC" | /usr/bin/wc -l`


if [ $COUNT = 0 ]; then
        echo "Cluster OK. $MASTER is set as primary Node"
        exit 0
else
        echo "Cluster changed. $SLAVE is set as primary Node!  Please check!!!"
        exit 1
fi

