#!/bin/bash

PATH=$PATH:/usr/sbin
#export HOME=$(getent passwd $(whoami) |cut -d: -f6)
export HOME=/var/tmp

CONFIGURATION=$(sudo crm configure show)
if [ $? -ne 0 ]
then
        echo "ERROR - counld not get cluster configuration"
        exit 3
fi

if [[ "$CONFIGURATION" =~ "location cli-" ]]
then
        echo "CRITICAL - cluster does contain cli constraints, delete them!"
        exit 2
else
        echo "OK - cluster does not contain cli constraints"
        exit 0
fi

echo "CRITICAL - something went horribly wrong!"
exit 2
